[package]
name = "pepper-parser"
version = "0.1.0"
authors = ["artronics <jalalhosseiny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"nom" = "5.1.0"

[dev-dependencies]
"pretty_assertions" = "0.6.1"
